version: '3'
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports:
      - '3000:3000' # expose-to-the-world : only-in-the-docker
    container_name: nest-todo-app-be
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgdata:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
